image: python:3.7.3

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - ./install_requirements_dev.sh
  - . ./env/bin/activate

test:
  script:
    - mypy .
    - pytest
