image: python:3.7.3

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - ./install_requirements_dev.sh
  - . ./venv/bin/activate

test:
  script:
    - mypy .
    - pytest
    - ./lint.sh --disable=fixme

production:
  type: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cis19-technical-analysis.git
    - git push -f heroku master