image: python:3.7.4

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test
  - deploy

test:
  stage: test
  cache:
    paths:
      - .cache/pip
  script:
    - ./install_requirements_dev.sh
    - . ./venv/bin/activate
    - pytest -k "not smoke"
    - mypy .
    - ./lint.sh --disable=fixme,unused-argument,duplicate-code

staging:
  stage: deploy
  script:
    - git remote add heroku-personal https://heroku:$HEROKU_API_KEY@git.heroku.com/cis19-dr2-technical-analysis.git
    - git push -f heroku-personal HEAD:master

production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cis2019-technical-analysis.git
    - git push -f heroku HEAD:master
